# Generated by Django 3.2.7 on 2021-11-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(default='', max_length=4)),
                ('operationTime', models.IntegerField(default=False)),
                ('stopLossPrice', models.IntegerField(default=False)),
                ('inputPrice', models.IntegerField(default=False)),
                ('outputPrice', models.IntegerField(default=False)),
                ('pipValue', models.IntegerField(default=False)),
                ('riskPercentage', models.IntegerField(default=False)),
                ('comissions', models.IntegerField(default=False)),
                ('actionName', models.CharField(default='', max_length=100)),
                ('market', models.CharField(default='', max_length=50)),
                ('typeTrade', models.CharField(default='', max_length=4)),
                ('auto', models.CharField(default='', max_length=2)),
                ('userType', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
