# Generated by Django 3.2.7 on 2021-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='automated',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pip_value',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss_price',
            field=models.FloatField(default=False),
        ),
    ]
